### ISSUE TITLE
Corruption test fails

### ISSUE THREAD

**Issue by buybackoff** [bitcoin-core/leveldb#7]
I finally managed to compile this under MinGW and found that the _corruption test_ doesn't pass (all others are OK). The funny thing is that it doesn't pass because with the current design it is not possible to corrupt the data in the way the test tries, i.e. it is not possible to read/write already opened files with the current combination of `CreateFileW` flags in `env_win.cc`.

Is this expected? Do you have the same result?

I post the issue here because this file was created in this repo and not in the upstream.

**Comment by laanwj** [comment]
Is this fixed by #17 (which has been merged)?

**Comment by buybackoff** [comment]
Have no idea, stopped trying to use LevelDB long time ago.
